#include "blockDB.h"

namespace BlockDB {
BasicBlock     air(0);
BasicBlock     stone(1);
BasicBlock     grassBlock(2);
BasicBlock     dirt(3);
BasicBlock     cobblestone(4);
BasicBlock     planks(5);
SaplingBlock   sapling(6);
BasicBlock     bedrock(7);
BasicBlock     water(8);
BasicBlock     waterStill(9);
BasicBlock     lava(10);
BasicBlock     lavaStill(11);
BasicBlock     sand(12);
BasicBlock     gravel(13);
BasicBlock     goldOre(14);
BasicBlock     ironOre(15);
BasicBlock     coalOre(16);
BasicBlock     logBlock(17);
BasicBlock     leaves(18);
BasicBlock     sponge(19);
BasicBlock     glass(20);
BasicBlock     lapisOre(21);
BasicBlock     lapisBlock(22);
BasicBlock     dispenser(23);
BasicBlock     sandStone(24);
NoteBlock      noteBlock(25);
BasicBlock     bed(26);
BasicBlock     poweredRail(27);
BasicBlock     buttonRail(28);
BasicBlock     stickyPiston(29);
BasicBlock     cobweb(30);
BasicBlock     tallGrass(31, 0.0f);
BasicBlock     deadBush(32, 0.0f);
BasicBlock     piston(33);
BasicBlock     pistonExtension(34);
WoolBlock      wool(35);
BasicBlock     pistonMover(36, 0.0f);
BasicBlock     yellowFlower(37, 0.0f);
BasicBlock     redFlower(38, 0.0f);
BasicBlock     mushroom(39, 0.0f);
BasicBlock     mushroom2(40, 0.0f);
BasicBlock     goldBlock(41);
BasicBlock     ironBlock(42);
BasicBlock     slabBlock(43);
BasicBlock     slab(44);
BasicBlock     brick(45);
BasicBlock     tnt(46, 0.0f);
BasicBlock     bookshelf(47);
BasicBlock     mossyStone(48);
BasicBlock     obsidian(49);
BasicBlock     torch(50, 0.0f);
BasicBlock     fire(51);
BasicBlock     spawner(52);
BasicBlock     stairs(53);
BasicBlock     chest(54);
BasicBlock     redstone(55, 0.0f);
BasicBlock     diamondOre(56);
BasicBlock     diamondBlock(57);
WorkbenchBlock workbench(58);
BasicBlock     crops(59, 0.0f);
BasicBlock     shovDirt(60);
BasicBlock     furnace(61);
BasicBlock     furnaceActive(62);
BasicBlock     sign(63);
BasicBlock     woodDoorFrame(64);
BasicBlock     ladder(65);
BasicBlock     rail(66);
BasicBlock     stoneStairs(67);
BasicBlock     signWall(68);
BasicBlock     lever(69, 0.0f);
BasicBlock     stonePressurePlate(70);
BasicBlock     ironDoorFrame(71);
BasicBlock     woodPressurePlate(72);
BasicBlock     actRedstoneOre(73);
BasicBlock     redstoneOre(74);
BasicBlock     unlitRedstoneTorch(75, 0.0f);
BasicBlock     redstoneTorch(76, 0.0f);
BasicBlock     stoneButton(77);
BasicBlock     snow(78);
BasicBlock     iceBlock(79);
BasicBlock     snowBlock(80);
BasicBlock     cactus(81);
BasicBlock     clayBlock(82);
BasicBlock     sugarcane(83, 0.0f);
BasicBlock     jukebox(84);
BasicBlock     fence(85);
BasicBlock     pumpkin(86);
BasicBlock     netherrack(87);
BasicBlock     soulsand(88);
BasicBlock     glovestone(89);
BasicBlock     portal(90);
BasicBlock     litPumpkin(91);
BasicBlock     cake(92);
BasicBlock     redstoneRepeater(93, 0.0f);
BasicBlock     redstoneRepeaterActivated(94, 0.0f);
BasicBlock     lockedChest(95, 0.0f);
BasicBlock     trapdoor(96);
} // namespace BlockDB
