#include "itemDB.h"

namespace ItemDB {
Item         ironShovel(0);
Item         ironPickaxe(1);
Item         ironAxe(2);
ItemLighter  lighter(3);
Item         apple(4);
ItemBow      bow(5);
Item         arrow(6);
Item         coal(7);
Item         diamond(8);
Item         ironIngot(9);
Item         goldIngot(10);
ItemSword    ironSword(11, ToolMaterial::Iron);
ItemSword    woodenSword(12, ToolMaterial::Wood);
Item         woodenShovel(13);
Item         woodenPickaxe(14);
Item         woodenAxe(15);
Item         stoneSword(16);
Item         stoneShovel(17);
Item         stonePickaxe(18);
Item         stoneAxe(19);
ItemSword    diamondSword(20, ToolMaterial::Diamond);
Item         diamondShovel(21);
Item         diamondPickaxe(22);
Item         diamondAxe(23);
Item         stick(24);
Item         bowl(25);
Item         soup(26);
ItemSword    goldenSword(27, ToolMaterial::Gold);
Item         goldenShovel(28);
Item         goldenPickaxe(29);
Item         goldenAxe(30);
Item         string(31);
Item         feather(32);
Item         gunpowder(33);
Item         woodenHoe(34);
Item         stoneHoe(35);
Item         ironHoe(36);
Item         diamondHoe(37);
Item         goldenHoe(38);
Item         seeds(39);
Item         wheat(40);
Item         bread(41);
ItemArmor    leatherHelmet(42, ArmorType::Head);
ItemArmor    leatherChest(43, ArmorType::Chest);
ItemArmor    leatherLeggings(44, ArmorType::Pants);
ItemArmor    leatherBoots(45, ArmorType::Boots);
ItemArmor    chainHelmet(46, ArmorType::Head);
ItemArmor    chainChest(47, ArmorType::Chest);
ItemArmor    chainLeggings(48, ArmorType::Pants);
ItemArmor    chainBoots(49, ArmorType::Boots);
ItemArmor    ironHelmet(50, ArmorType::Head);
ItemArmor    ironChest(51, ArmorType::Chest);
ItemArmor    ironLeggings(52, ArmorType::Pants);
ItemArmor    ironBoots(53, ArmorType::Boots);
ItemArmor    diamonHelmet(54, ArmorType::Head);
ItemArmor    diamonChest(55, ArmorType::Chest);
ItemArmor    diamonLeggings(56, ArmorType::Pants);
ItemArmor    diamonBoots(57, ArmorType::Boots);
ItemArmor    goldenHelmet(58, ArmorType::Head);
ItemArmor    goldenChest(59, ArmorType::Chest);
ItemArmor    goldenLeggings(60, ArmorType::Pants);
ItemArmor    goldenBoots(61, ArmorType::Boots);
Item         flint(62);
Item         rawPork(63);
Item         cookedPork(64);
Item         painting(65);
Item         goldenApple(66);
Item         sign(67);
Item         door(68);
Item         bucket(69);
Item         waterBucket(70);
Item         lavaBucket(71);
Item         minecart(72);
Item         saddle(73);
Item         ironDoor(74);
Item         redstonePowder(75);
ItemSnowball snowBall(76);
Item         boat(77);
Item         leather(78);
Item         milkBucket(79);
Item         brick(80);
Item         clay(81);
Item         sugarCane(82);
Item         paper(83);
Item         book(84);
Item         slime(85);
Item         chestMinecart(86);
Item         furnaceMinecart(87);
Item         egg(88);
Item         compass(89);
Item         fishingRod(90);
Item         clockItem(91);
Item         glowDust(92);
Item         fish(93);
Item         cookedFish(94);
Item         genericDye(95);
Item         bone(96);
Item         sugar(97);
Item         cake(98);
Item         bed(99);
Item         redstoneRepeater(100);
Item         cookie(101);
Item         map(102);
Item         shears(103);
} // namespace ItemDB
